@startuml
class Fournisseur {
	**id : int**
	nom : string
	email : string
	telephone : string
}

class Client {
	**id : int**
	nom : string
	prenom : string
	email : string
}

class Produit {
	**id : int**
	nom : string
	description : string
	ref_fournisseur : string
	prix_achat : string
	image : string
	stock : int
	actif : bool
	<color:#0000dd>sous_Categorie : SousCategorie</color>
}

class SousCategorie {
	**id : int**
	nom : string
	image : string
	<color:#0000dd>Categorie : Categorie</color>
	<color:#0000dd>produits : Produit[]</color>
}

class Commerciaux {
	**id : int**
	nom : string
	prenom : string
	email : string
	telephone : string
}

class Categorie {
	**id : int**
	nom : string
	<color:#0000dd>sousCategories : SousCategorie[]</color>
}

Produit "*"--"1" SousCategorie
SousCategorie "*"--"1" Categorie


hide methods

hide circle

@enduml
